#!/bin/sh

gcc="gcc -O3"

prefix=$1

exit_on_error() {
  $* || exit 1
}

compile_libscrypt() {
  path_scrypt=source/derivations/scrypt
  include_paths="-I $path_scrypt -I $path_scrypt/lib/crypto -I $path_scrypt/lib/util"
  path_libcperciva="$path_scrypt/libcperciva"
  include_paths="$include_paths -I $path_libcperciva/alg -I $path_libcperciva/cpusupport -I $path_libcperciva/crypto -I $path_libcperciva/util"
  # "-lm" links the standard "math" library
  exit_on_error $gcc -shared -fPIC -lm $include_paths -DHAVE_CONFIG_H -o temp/libscrypt.so source/scrypt.c
}

compile_scrypt_kdf() {
  ld_flags="-Wl,-rpath,$prefix/usr/lib:."
  exit_on_error $gcc source/cli.c $ld_flags -o temp/scrypt-kdf --std=c11 -L./temp -lscrypt -lm
}

mkdir -p temp
compile_libscrypt
compile_scrypt_kdf
